server:
  port: 18087
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

# feign调用的数据太大时要增加ribbon中读取时间连接时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

  #rabbitmq:
  #  host: 192.168.25.138


# 生成静态页的位置
pagePath: D:/IdeaProjects/changgou_66/changgou-web/changgou-web-item/src/main/resources/templates/items