server:
  port: 18090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.186.132:3306/changgou_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.186.132
    port: 6379
  rabbitmq:
    host: 192.168.186.132
    port: 5672
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.changgou.order.pojo

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000

# feign调用的数据太大时要增加ribbon中读取时间连接时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000