spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
#        - id: changgou_goods_route
#          uri: http://localhost:18081
#          predicates:
#            - Host=cloud.itheima.com**

#        - id: changgou_goods_route
#          uri: http://localhost:18081
#          predicates:
#            - Path=/brand/**

        # 商品微服务路由
        - id: changgou_goods_route
          uri: lb://goods
#          uri: http://localhost:18081
          predicates:
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,
              /api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
#            - PrefixPath=/brand
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的factory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5

        # 用户微服务路由
        - id: changgou_user_route
          uri: lb://user
          predicates:
          - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
          - StripPrefix=1
          - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的factory
            args:
              key-resolver: "#{@ipKeyResolver}"
              redis-rate-limiter.replenishRate: 5
              redis-rate-limiter.burstCapacity: 5

        # 订单微服务路由
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**
          filters:
            - StripPrefix=1

        # 订单Web微服务路由
        - id: changgou_order-web_route
          uri: lb://order-web
          predicates:
            - Path=/webapi/wcart/**,/webapi/categoryReport/**,/webapi/orderConfig/**,/webapi/order/**,/webapi/orderItem/**,/webapi/orderLog/**,/webapi/preferential/**,/webapi/returnCause/**,/webapi/returnOrder/**,/webapi/returnOrderItem/**,,/webapi/worder/**
          filters:
            - StripPrefix=1

        # 支付微服务路由
        - id: changgou_pay_route
          uri: lb://pay
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1

        # 秒杀微服务路由
        - id: changgou_seckill_route
          uri: lb://seckill
          predicates:
            - Path=/api/seckillOrder/**,/api/seckillGoods/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.186.132
    port: 6379

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true